<a href="https://colab.research.google.com/github/lucianodinizrosa/lrosa/blob/master/DS_Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variables & Code Style

- [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)

In [0]:
nome = 'felipe'

In [0]:
nome_completo = 'Felipe Brandao' # NomeCompleto nomeCompleto nomecompleto (snake case)

# Data Types

![img](https://miro.medium.com/max/1316/1*uFlTNY4W3czywyU18zxl8w.png)

## Tipos Primitivos
Integer `int`, Float `float`, Boolean `bool` e String `str`

### Int `immutable`

In [0]:
idade = 30

In [0]:
type(idade)

int

### Float `immutable`

In [0]:
altura = 1.80

In [0]:
type(altura)

float

### String `immutable`

In [0]:
nome = 'Joao'

In [0]:
type(nome)

str

### None `immutable`

In [0]:
nome_completo = None

In [0]:
type(nome_completo)

NoneType

### Bool `immutable`

In [0]:
esta_chovendo = False

In [0]:
nao_esta_chovendo = True

## Tipos Avançados
Listas `list`, Tuplas `tuple`, Dicionários `dict` e Conjuntos `set`

### Lists `mutable`

In [0]:
lista = [7, 4, 8]

In [0]:
type(lista)

list

In [0]:
lista[2] # Indexing

8

In [0]:
lista[3]

IndexError: ignored

In [0]:
lista.append(2)

In [0]:
lista

[7, 4, 8, 2]

In [0]:
lista.pop()

2

In [0]:
lista

[7, 4, 8]

### Tuple `immutable`

In [0]:
tupla = (3, 4, 5)

In [0]:
type(tupla)

tuple

### Dictionaries `mutable`

In [0]:
dicionario = {'nome': 'felipe'}

In [0]:
dicionario['nome']

'felipe'

In [0]:
dicionario['nome_completo']

KeyError: ignored

#### `Exemplo 1:` Mapear Elementos de uma lista usando um dicionários

In [0]:
lista_paises = [1, 2, 3, 1, 2, 1]

In [0]:
mapeamento = {
    1: 'Brasil',
    2: 'Argentina',
    3: 'Estados Unidos'
}

In [0]:
mapeamento[lista_paises[0]]

'Brasil'

### Sets `set`

In [0]:
a = {5, 6, 4}

In [0]:
type(a)

set

# Operators

### Arithmetics

In [0]:
3 + 4 # Soma (float, int)

7

In [0]:
3 - 4 # Substração (float, int)

-1

In [0]:
3 / 4 # Divisão (float, int)

0.75

In [0]:
3 * 4 * 7  # Multiplicação (float, int)

84

In [0]:
'felipe' + 'brandao' # Concatenação (str)

'felipebrandao'

In [0]:
'felipe' + ' ' + 'brandao'

'felipe brandao'

In [0]:
'felipe' - 'brandao' # Não faz sentido (str)

TypeError: ignored

In [0]:
'felipe' * 'brandao' # Não faz sentido (str e str)

TypeError: ignored

In [0]:
'felipe' * 8 # Repetição (str e int)

'felipefelipefelipefelipefelipefelipefelipefelipe'

In [0]:
'felipe' * 8.9 # Não faz sentido (str e float)

TypeError: ignored

#### `Exercício 2:` Operadores aritméticos para dics, tuples e lists

### Comparison

In [0]:
3 > 4 # (float, int)

False

In [0]:
'w' > 'c' # (str)

True

In [0]:
3 < 4

True

In [0]:
3 >= 2

True

In [0]:
4 <= 5

True

In [0]:
4 != 5 # Diferente de <>

True

In [0]:
4 == 5

False

### Logicals

In [0]:
True and True 

True

In [0]:
True or False

True

In [0]:
not True

False

In [0]:
not False

True

### Membership

In [0]:
'e' in 'felipe' # (str)

True

In [0]:
4 in [4, 5] # (list, tuple)

True

In [0]:
4 not in [4, 5]

False

### Identity

In [0]:
True == True

True

In [0]:
True == 1

True

In [0]:
True is 1

False

In [0]:
'felipe' == 'felipe'

True

In [0]:
4 == 5

False

# Indexing

![img](https://i1.wp.com/codingmeta.com/wp-content/uploads/2017/09/vikad.png?resize=1100%2C366)

In [0]:
nomes = ['felipe', 'joao']

In [0]:
nomes[0] # Primeira posição

'felipe'

In [0]:
nomes[-2]

'felipe'

In [0]:
nomes = ('felipe', 'joao')

In [0]:
nomes[3]

IndexError: ignored

In [0]:
mapeamento = {
    1: 'Brasil',
    2: 'Argentina',
    3: 'Estados Unidos'
}

In [0]:
mapeamento[0]

KeyError: ignored

In [0]:
estados = {
    'pr': 'Paraná',
    'sp': 'São Paulo'
}

In [0]:
pessoas = {
    'felipe': {
        'idade': 25,
        'cidade': 'Curitiba',
        'notas': [10, 3, 2]
    }
}

In [0]:
pessoas['felipe']['notas'][0]

10

In [0]:
pessoas['felipe']['cidade'][0]

'C'

In [0]:
estados['pr']

'Paraná'

In [0]:
nome = 'felipe'

In [0]:
nome[-1]

'e'

In [0]:
idade = 20.0

In [0]:
idade[0]

TypeError: ignored

# Slicing

In [0]:
cidades = ['São Paulo', 'Curitiba', 'Rio de Janeiro']

In [0]:
cidades[1:3]

['Curitiba', 'Rio de Janeiro']

In [0]:
cidade = 'São Paulo'

In [0]:
cidade[4:9]

'Paulo'

# Type Methods

In [0]:
nome = 'felipe'

In [0]:
lista = [5, 7, 3]

# Conditionals (`if`)

![img](https://files.realpython.com/media/t.78f3bacaa261.png)

In [0]:
esta_chovendo = True

In [0]:
if esta_chovendo:
  print('Está Chovendo')

Está Chovendo


In [0]:
nota = 40

In [0]:
if not nota > 60:
  print('Passou')

Passou


In [0]:
coisas_pendentes = ['arrumar o quarto', 2, 3]

In [0]:
if not coisas_pendentes:
  print('Estou livre.')
else:
  if len(coisas_pendentes) == 1:
    print('Tenho poucas coisas a fazer.')
  else:
    if len(coisas_pendentes) > 2:
      print('Tenho muitas coisas.')
    else:
      print('Muitas coisas mesmo.')

Tenho muitas coisas.


In [0]:
if not coisas_pendentes and esta_chovendo > 0:
  print('Estou livre.')
elif len(coisas_pendentes) == 1:
  print('Tenho poucas coisas a fazer.')
elif len(coisas_pendentes) > 2:
  print('Tenho muitas coisas.')
else:
  print('Muitas coisas mesmo.')

Tenho muitas coisas.


# Functions

In [0]:
import math

![img](https://cdn1.byjus.com/wp-content/uploads/2016/04/The-Distance-Formula.gif)

In [0]:
def calcula_distancia(x1, x2):
  return x1 - x2

In [0]:
calcula_distancia(5, 10)

-5

In [0]:
def calcula_distancia_entre_pontos(x1, x2, y1, y2):
  return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

In [0]:
calcula_distancia_entre_pontos(1, 2, 3, 9)

6.082762530298219

In [0]:
ponto_a = (1, 3)
ponto_b = (2, 9)

In [0]:
def calcula_distancia_entre_pontos(ponto1, ponto2):
  return math.sqrt((ponto1[0] - ponto2[0])**2 + (ponto1[1] - ponto2[1])**2)

In [0]:
calcula_distancia_entre_pontos(ponto_a, ponto_b)

6.082762530298219

In [0]:
nota_um = 50
nota_dois = 40

In [0]:
def calcula_nota_final(nota_um, nota_dois, nota_tres = None):

  media = (nota_um + nota_dois) / 2

  if nota_tres is not None:
    media_final = (media + nota_tres) / 2
    return media_final

  return media

In [0]:
calcula_nota_final(nota_um,  nota_dois, 60)

52.5

In [0]:
def esta_aprovado(nota_um, nota_dois, nota_tres = None):

  nota_minima = 50

  media_final = calcula_nota_final(nota_um, nota_dois, nota_tres)

  if media_final >= nota_minima:
    return  True
  return False

# Loops (`for`, `while`)

In [0]:
import numpy as np

In [0]:
for i in range(0, len(notas)):
  print(notas[i] > 50)

True
False
False
True
False
False
False


In [0]:
notas = [60, 20, 30, 60, 45, 34, 23]

In [0]:
nota_maior_media = []
for nota in notas:
  nota_maior_media.append(nota > 50)

In [0]:
nota_maior_media

[True, False, False, True, False, False, False]

### Iterando com `numpy`

In [0]:
import numpy as np

In [0]:
number = 10

In [0]:
y_real = np.random.rand(number)
y_predicted = np.random.rand(number)

In [0]:
%%time
erros = []
for i in range(len(y_real)):

  erro = abs(y_real[i] - y_predicted[i])
  erros.append(erro)

soma = 0
conta = 0
for erro in erros:
  soma = soma + erro
  conta = conta + 1

media_erro = soma / conta
print(media_erro)


KeyboardInterrupt



In [0]:
%%time
soma = 0
for i in range(len(y_real)):

  erro = abs(y_real[i] - y_predicted[i])
  soma = soma + erro

print(soma / len(y_real))

0.33364168192786625
CPU times: user 815 ms, sys: 0 ns, total: 815 ms
Wall time: 821 ms


In [0]:
%%time
def absolute_error(y_real, y_predicted):
  return abs(y_real - y_predicted)

soma = 0
for i in range(len(y_real)):
  soma = soma + absolute_error(y_real[i], y_predicted[i])

print(soma / len(y_real))

0.33364168192786625
CPU times: user 767 ms, sys: 0 ns, total: 767 ms
Wall time: 768 ms


In [0]:
%%time
np.absolute(y_real - y_predicted).mean()

CPU times: user 334 ms, sys: 282 ms, total: 616 ms
Wall time: 616 ms


0.3333555890130774

# Functions (Avançado)

#### Parametros default (`parametro = default`)

In [0]:
def nome_completo(nome, sobrenome = None):
  print('nome:', nome)
  if sobrenome is not None:
    print('sobrenome:', sobrenome)

In [0]:
nome_completo('Felipe', 'Brandao')

nome: Felipe
sobrenome: Brandao


In [0]:
nome_completo('Felipe')

nome: Felipe


In [0]:
# Cuida com a posição dos parâmetros
def nome_copleto(nome = None, sobrenome):
  print('nome:', nome)
  if sobrenome is not None:
    print('sobrenome:', sobrenome)

SyntaxError: ignored

#### Parâmetros por posição (`position`) vs. nome (`keyword`)

In [0]:
def nome_completo(nome, sobrenome = None):
  print('nome:', nome)
  if sobrenome is not None:
    print('sobrenome:', sobrenome)

In [0]:
nome_completo('Felipe', 'Brandao')

nome: Felipe
sobrenome: Brandao


In [0]:
nome_completo('Brandao', 'Felipe')

nome: Brandao
sobrenome: Felipe


In [0]:
nome_completo(nome='Felipe', sobrenome='Brandao')

nome: Felipe
sobrenome: Brandao


In [0]:
nome_completo(sobrenome='Brandao', nome='Felipe')

nome: Felipe
sobrenome: Brandao


In [0]:
def nome_completo(nome, segundo_nome = None, sobrenome = None):
  print('nome:', nome)
  print('segundo_nome:', segundo_nome)
  print('sobrenome:', sobrenome)

In [0]:
nome_completo('Felipe', sobrenome='Brandao')

nome: Felipe
segundo_nome: None
sobrenome: Brandao


#### `*args` e `**kwargs`

A gente encontra isso em vários bibliotecas de data science. Exemplos:

- [`matplotlib.pyplot.plot`](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.plot.html)
- [`sklearn.model_selection.train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)
- [`sklearn.model_selection.check_cv`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.check_cv.html#sklearn.model_selection.check_cv)

**Leituras Básicas**
- [Python: entendendo o uso de *args e **kwargs em funções e métodos](https://medium.com/rafaeltardivo/python-entendendo-o-uso-de-args-e-kwargs-em-fun%C3%A7%C3%B5es-e-m%C3%A9todos-c8c2810e9dc8)
- [Python - O básico de funções](http://devfuria.com.br/python/functions/)

**Leituras Avançadas**
- [PEP 570 -- Python Positional-Only Parameters](https://www.python.org/dev/peps/pep-0570/)
- [PEP 468 -- Preserving the order of **kwargs in a function.](https://www.python.org/dev/peps/pep-0468/)
- [PEP 3102 -- Keyword-Only Arguments](https://www.python.org/dev/peps/pep-3102/)

##### Args

In [0]:
def printa_nomes(*nomes):
  print(nomes)

In [0]:
printa_nomes() # Agora a variavel nomes é uma tupla, mesmo que voce não passe nada

()


In [0]:
printa_nomes('felipe', 'brandao')

('felipe', 'brandao')


##### Kwargs

In [0]:
def recebe_varios_parametros_por_nome(**parametros):
  print(parametros)

In [0]:
recebe_varios_parametros_por_nome() # Agora é um dict , mesmo que você não passe nada

{}


In [0]:
recebe_varios_parametros_por_nome(nome='felipe', sobrenome='brandao')

{'nome': 'felipe', 'sobrenome': 'brandao'}


##### Exemplo simulando a função `train_test_split()` do `sklearn`

In [0]:
import numpy as np

In [0]:
def train_test_split(*arrays, test_size):
  print('test_size:', test_size)
  print('variavel com * arrays:', arrays)
  for array in arrays:
    print('elemento do array:', array)

In [0]:
array_um = np.array([3, 4])

In [0]:
array_dois = np.array([5, 6])

In [0]:
train_test_split(array_um, array_dois, test_size=0.2)

test_size: 0.2
variavel com * arrays: (array([3, 4]), array([5, 6]))
elemento do array: [3 4]
elemento do array: [5 6]


In [0]:
def train_test_split(*arrays, **options):
  print('test_size:', options['test_size'])
  print('variavel com * arrays:', arrays)
  for array in arrays:
    print('elemento do array:', array)

In [0]:
train_test_split(array_um, array_dois, train_size=0.2, test_size=0.3, nome='felipe')

test_size: 0.3
variavel com * arrays: (array([3, 4]), array([5, 6]))
elemento do array: [3 4]
elemento do array: [5 6]


##### `dict.get()` vs. `dict[]`

In [0]:
estados = {
    'pr': 'Paraná',
    'sp': 'São Paulo'
}

In [0]:
estados['rj']

KeyError: ignored

In [0]:
estados.get('rj')

#### Functions: First-class Citizen

In [0]:
def hello(nome):
  print('Hello,', nome)

In [0]:
hello('Felipe')

Hello, Felipe


In [0]:
a = hello # Você pode colocar funções em variáveis

In [0]:
a('felipe')

Hello, felipe


###### Exemplo: Passar funções para funções

In [0]:
def absolute_error(x, y):
  return abs(x - y)

In [0]:
def normal_error(x, y):
  return x - y

In [0]:
normal_error(array_um, array_dois)

array([-2, -2])

In [0]:
def calculate_error(x, y, metric):
  return metric(x, y)

In [0]:
calculate_error(array_um, array_dois, absolute_error)

array([2, 2])

In [0]:
calculate_error(array_um, array_dois, normal_error)

array([-2, -2])

#### `lambda` (funções anonimas)

- [Lambdas with groupbys](https://mode.com/python-tutorial/pandas-groupby-and-python-lambda-functions/)
- [Programação Funcional](http://nasemanadaprova.blogspot.com/2015/01/programacao-funcional-python.html)

In [0]:
a = lambda x: x ** 2 # É a mesma coisa que escrever def a(x): return x ** 2

###### Exemplo: Mapear um dicionário para uma lista

In [0]:
estados = ['pr', 'sp', 'pr', 'PR', 'par']

In [0]:
dicionario = {
    'pr': 'Paraná',
    'sp': 'São Paulo',
    'par': 'Paraná',
    'PR': 'Paraná'
}

In [0]:
# Tentantiva 1: usando for loops
nova_lista = []
for estado in estados:
  nova_lista.append(dicionario[estado])
nova_lista

In [0]:
# Tentantiva 2: usando lambda e map
lista(map(lambda x: dicionario[x], estados))

('Paraná', 'São Paulo', 'Paraná', 'Paraná', 'Paraná')

###### Exemplo: Aplicando lambdas para filtrar dataframes

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('sample_data/california_housing_test.csv')

In [0]:
df[df['population'].apply(lambda x: x > 600 and x < 1000)]

longitude  latitude  ...  median_income  median_house_value
1       -118.30     34.26  ...         3.5990            176500.0
4       -119.67     36.33  ...         2.9375             81700.0
5       -119.56     36.51  ...         1.6635             67000.0
6       -121.43     38.63  ...         1.6641             67000.0
18      -118.88     34.21  ...         6.5851            300000.0
...         ...       ...  ...            ...                 ...
2986    -118.25     33.93  ...         1.1346             85400.0
2991    -117.17     34.28  ...         7.1997            253800.0
2993    -117.91     33.60  ...         5.1048            500001.0
2997    -119.70     36.30  ...         2.2895             62000.0
2999    -119.63     34.42  ...         8.5608            500001.0

[763 rows x 9 columns]

#### [List Comprehensions](https://pythonacademy.com.br/blog/list-comprehensions-no-python)

In [0]:
compras = [20.54, 39.7, 3.9, 12.3]

In [0]:
compras_filtradas = [element for element in compras if element > 12]

In [0]:
compras_filtradas

[20.54, 39.7, 12.3]